### ISSUE TITLE
Image build failed

### ISSUE THREAD

**Issue by jameswu0629** [privacysandbox/protected-auction-key-value-service#69]
- Branch: release-0.17

- Build command: 
```
./builders/tools/bazel-debian run //production/packaging/aws/data_server:copy_to_dist --config=local_instance --config=aws_platform --config=nonprod_mode
```

- Error messages:

```
WARNING: Download from https://storage.googleapis.com/quiche-envoy-integration/googleurl_9cdb1f4d1a365ebdbcbf179dadf7f8aa5ee802e7.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

ERROR: An error occurred during the fetch of repository 'com_google_googleurl':
   Traceback (most recent call last):
        File "/bazel_root/build_ubuntu_b77b7d5/dee7a9dc180828a39c0a3eb7b8774225/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/googleurl_9cdb1f4d1a365ebdbcbf179dadf7f8aa5ee802e7.tar.gz] to /bazel_root/build_ubuntu_b77b7d5/dee7a9dc180828a39c0a3eb7b8774225/external/com_google_googleurl/temp7088255967701992841/googleurl_9cdb1f4d1a365ebdbcbf179dadf7f8aa5ee802e7.tar.gz: GET returned 404 Not Found
ERROR: /src/workspace/WORKSPACE:37:24: fetching http_archive rule //external:com_google_googleurl: Traceback (most recent call last):
        File "/bazel_root/build_ubuntu_b77b7d5/dee7a9dc180828a39c0a3eb7b8774225/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/googleurl_9cdb1f4d1a365ebdbcbf179dadf7f8aa5ee802e7.tar.gz] to /bazel_root/build_ubuntu_b77b7d5/dee7a9dc180828a39c0a3eb7b8774225/external/com_google_googleurl/temp7088255967701992841/googleurl_9cdb1f4d1a365ebdbcbf179dadf7f8aa5ee802e7.tar.gz: GET returned 404 Not Found
ERROR: @com_google_googleurl//build_config:system_icu :: Error loading option @com_google_googleurl//build_config:system_icu: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/googleurl_9cdb1f4d1a365ebdbcbf179dadf7f8aa5ee802e7.tar.gz] to /bazel_root/build_ubuntu_b77b7d5/dee7a9dc180828a39c0a3eb7b8774225/external/com_google_googleurl/temp7088255967701992841/googleurl_9cdb1f4d1a365ebdbcbf179dadf7f8aa5ee802e7.tar.gz: GET returned 404 Not Found
```

**Comment by lx3-g** [comment]
Hi @jameswu0629 ,

Thnx for reporting the issue. This issue has started happening recently. We aware of the issue and are working on a fix.
We will update this github issue once it is fixed.

**Comment by lx3-g** [comment]
Our GA 1.0 is out. Please use that version. release-0.17 is no longer supported.
